src/Entity/Region.php
<?php

namespace App\Entity;

use App\Repository\RegionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass=RegionRepository::class)
 */
class Region
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $carte_svg;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom_bdd;

    /**
     * @ORM\OneToMany(targetEntity=Departement::class, mappedBy="region")
     */
    private $departements;

    /**
     * @ORM\ManyToOne(targetEntity=SuperRegion::class, inversedBy="regions")
     */
    private $superRegion;

    public function __construct()
    {
        $this->departements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescritpion(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCarteSvg(): ?string
    {
        return $this->carte_svg;
    }

    public function setCarteSvg(string $carte_svg): self
    {
        $this->carte_svg = $carte_svg;

        return $this;
    }

    public function getNomBdd(): ?string
    {
        return $this->nom_bdd;
    }

    public function setNomBdd(string $nom_bdd): self
    {
        $this->nom_bdd = $nom_bdd;

        return $this;
    }

    /**
     * @return Collection|Departement[]
     */
    public function getDepartements(): Collection
    {
        return $this->departements;
    }

    public function addDepartement(Departement $departement): self
    {
        if (!$this->departements->contains($departement)) {
            $this->departements[] = $departement;
            $departement->setRegion($this);
        }

        return $this;
    }

    public function removeDepartement(Departement $departement): self
    {
        if ($this->departements->removeElement($departement)) {
            // set the owning side to null (unless already changed)
            if ($departement->getRegion() === $this) {
                $departement->setRegion(null);
            }
        }

        return $this;
    }

    public function getSuperRegion(): ?SuperRegion
    {
        return $this->superRegion;
    }

    public function setSuperRegion(?SuperRegion $superRegion): self
    {
        $this->superRegion = $superRegion;

        return $this;
    }
}

src/Form/RegionType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RegionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('carte_svg')
            ->add('nom_bdd')
            ->add('departements')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/RegionsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Region;
use App\Entity\SuperRegion;

class RegionsController extends AbstractController
{
    /**
     * @Route("/regions/{id}", name="regions")
     */
    public function index($id): Response
    {

        $superRegion = $this->getDoctrine()->getRepository(SuperRegion::class)->findOneBy(["nomBdd"=>$id]);
        return $this->render('regions/index.html.twig', [
            'superRegion' => $superRegion
        ]);

    
    }
    /**
     * @Route("/region/{nom}", name="region")
     */
    public function region($nom): Response
    {

        $region = $this->getDoctrine()->getRepository(Region::class)->findOneBy(["nom_bdd"=>$nom]);
        // dd($region);
        return $this->render('regions/region.html.twig', [
            'region' => $region
        ]);

       
    }

}

templates/regions/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} REGION {{ superRegion.name }}{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
  
<div class="example-wrapper">
    <h1> VOUS VISITEZ LA REGION {{ superRegion.name|upper }}</h1>
{# <?xml version="1.0" encoding="utf-8"?> #}
<!-- Generator: Adobe Illustrator 25.2.3, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->

{{ superRegion.carte|raw }}
{% for region in superRegion.regions %}

<h2>{{ region.name}}</h2>
{# <div>{{ region.sous_region}}</div> #}
{% endfor %}
{% endblock %}
    
  

templates/regions/region.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h1 class="text-center"> BIENVENUE EN {{ region.name|upper }}</h1>
{# {{ dump(region)}} #}
<div class="row">
    <div class="col-12 col-md-4">
        <div class="carte-region">
        {{ region.carteSvg|raw }}
        </div>
    </div>
    <div class="col-12 col-md-8">
    {% if region.description is defined and region.description is not null %}
    {{ region.description|raw }}
    {% endif %}
    </div>
</div>



{#{% for departement in region.departements %}#}

{#<h2>{{ departement.name}}</h2>#}
{# <div>{{ region.sous_region}}</div> #}
 {#{% endfor %}#}

 {% endblock %}